name: ww_fresh # Atau nama environment yang kamu inginkan
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - setuptools   # <--- TAMBAHKAN INI
  - wheel        # <--- TAMBAHKAN INI
  - pyramid
  - sqlalchemy
  - psycopg2-binary
  - alembic
  - pyramid_tm
  - zope.sqlalchemy
  - waitress  
  - passlib[bcrypt]
  - requests
  # Jika ada paket lain dari setup.py/pyproject.toml yang ingin kamu kelola via Conda,
  # bisa ditambahkan di sini. Sisanya akan diurus pip.



